### ISSUE TITLE
End of replies from eredis_r_reply(r)

### ISSUE THREAD

**Issue by aflin** [EulerianTechnologies/eredis#10]
I am doing a variable number of `eredis_r_append_cmd()` and a final `reply=eredis_r_cmd()`.

When checking replies with `reply = eredis_r_reply( r )`,  I have no idea how many commands were issued (I could count, but eredis through r->cmds_replied already knows this).  Fortunately `reply==NULL` when no more replies are available, so I can just iterate through the replies.  Unfortunately it prints out an error message.  Is getting to the end of replies really an error?  Is there something else I'm missing?

I'd just do the same check in my code for `(r->cmds_replied >= r->cmds_nb)`, but apparently that is not available outside the API.

From rw.c:
```
if (r->cmds_replied >= r->cmds_nb) {
    fprintf(stderr,
            "eredis: api misuse: all cmds are already replied: %d/%d\n",
            r->cmds_replied, r->cmds_nb);
    return NULL;
}
```

**Comment by guillaumef** [comment]
I understand. Let me explain.

In sync mode, the caller is supposed to control its input and output.
Each request is intentional, with probably different kind of reply structure, my opinion was to enforce the caller to also manage each reply intentionally.
Since the caller knows what kind of and how many replies to wait for, I think there is no reason to move this logic only in the api. It is the reason of this error message.
'api misuse' is a warning of "inconsistency" in the api usage and could detect possible errors in the caller code implementation (or a possible bug in eredis code).

The internal structure of eredis is not available to the caller. It is an Opaque structure, far better for code quality, and the reason you can not read cmds_replied/cmds_nb.
The caller has to implement its own counter of how many replies it has to wait for.

**Comment by aflin** [comment]
Thanks for the quick and thorough reply.
-A-
